config/routes.rb
    match "/search_results/all_related_elements" => "search_results#all_related_elements" , :as => "all_related_elements"
    match "/search_results/all_best_search_results" => "search_results#all_best_search_results" , :as => "all_best_search_results"
    match "/search_results/load_more_search_results" => "search_results#load_more_search_results" , :as => "load_more_search_results"
    match "/search_results/load_more_related_elements" => "search_results#load_more_related_elements" , :as => "load_more_related_elements"
    resources :search_results
        
    resources :requirements
    match "/activity_sequences/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/:activity_sequence_id/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/new_activity_instance" => "activity_sequences#new_activity_instance"
    match "/activity_sequences/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/:activity_sequence_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/my_activity_sequences" => "activity_sequences#my_activity_sequences" , :as => "my_activity_sequences"
    match "/activity_sequences/pick_it" => "activity_sequences#pick_it" , :as => "pick_it"
    match "/activity_sequences/get_activity" => "activity_sequences#get_activity" , :as => "get_activity"
    match "/activity_sequences/popup_show_activity_sequence" => "activity_sequences#popup_show_activity_sequence" , :as => "popup_show_activity_sequence"
    resources :activity_sequences
    
    match "/guides/show_activity" => "activity_sequences#show_activity"
    match "/guides/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/show_sequence" => "guides#show_sequence"
    match "/guides/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/select_sequence" => "guides#select_sequence"
    match "/guides/get_sequence" => "guides#get_sequence"
    match "/guides/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/new_sequence" => "guides#new_sequence"
    match "/guides/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/recommend_tools" => "guides#recommend_tools"
    match "/guides/recommend_people" => "guides#recommend_people"
    match "/guides/recommend_events" => "guides#recommend_events"
    match "/guides/popup_show_guide" => "guides#popup_show_guide", :as => "popup_show_guide"
    match "/guides/my_guides" => "guides#my_guides" , :as => "my_guides"
    match "/guides/pick_it" => "guides#pick_it" , :as => "pick_it"
    match "/guides/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    match "/guides/:guide_id/show_activity" => "activity_sequences#show_activity"
    match "/guides/:guide_id/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/:guide_id/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/:guide_id/show_sequence" => "guides#show_sequence"
    match "/guides/:guide_id/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/:guide_id/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/:guide_id/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/:guide_id/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/:guide_id/select_sequence" => "guides#select_sequence"
    match "/guides/:guide_id/get_sequence" => "guides#get_sequence"
    match "/guides/:guide_id/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/:guide_id/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/:guide_id/new_sequence" => "guides#new_sequence"
    match "/guides/:guide_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/:guide_id/recommend_tools" => "guides#recommend_tools"
    match "/guides/:guide_id/recommend_people" => "guides#recommend_people"
    match "/guides/:guide_id/recommend_events" => "guides#recommend_events"
    match "/guides/:guide_id/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    resources :guides
    match "/technological_settings/popup_show_technological_setting" => "technological_settings#popup_show_technological_setting" , :as => "popup_show_technological_setting"
    resources :technological_settings
    match "/contextual_settings/popup_show_contextual_setting" => "contextual_settings#popup_show_contextual_setting" , :as => "popup_show_contextual_setting"
    resources :contextual_settings
    resources :seeds

    match "/experiences/popup_show_experience" => "experiences#popup_show_experience", :as => "popup_show_experience"
    match "/experiences/new/from_guide/:guide_id" => "experiences#new", :as => "new_experience_from_guide"
    match "/experiences/my_experiences" => "experiences#my_experiences" , :as => "my_experiences"
    match "/experiences/get_element_excerpt" => "experiences#get_element_excerpt"    
    resources :experiences

    
    match "/users/popup_show_user" => "users#popup_show_user", :as => "popup_show_user"
    resources :users    
    match "/resources/list_devices" => "resources#list_devices" , :as => "list_devices"
    match "/resources/list_applications" => "resources#list_applications" , :as => "list_applications"
    match "/resources/list_people" => "resources#list_people" , :as => "list_people"
    match "/resources/list_events" => "resources#list_events" , :as => "list_events"            
    resources :resources
    match "/devices/popup_show_device" => "devices#popup_show_device", :as => "popup_show_device"
    resources :devices
    match "/applications/popup_show_application" => "applications#popup_show_application", :as => "popup_show_application"
    resources :applications
    match "/people/popup_show_person" => "people#popup_show_person", :as => "popup_show_person"
    resources :people
    match "/events/popup_show_event" => "events#popup_show_event", :as => "popup_show_event"
    resources :events
    match "/lectures/popup_show_lecture" => "lectures#popup_show_lecture", :as => "popup_show_lecture"
    resources :lectures
    match "/sites/popup_show_site" => "sites#popup_show_site", :as => "popup_show_site"
    resources :sites
    match "/documentaries/popup_show_documentary" => "documentaries#popup_show_documentary", :as => "popup_show_documentary"
    resources :documentaries
    match "/courses/popup_show_course" => "courses#popup_show_course", :as => "popup_show_course"
    resources :courses
    match "/articles/popup_show_article" => "articles#popup_show_article", :as => "popup_show_article"
    resources :articles
    match "/lres/popup_show_lre" => "lres#popup_show_lre", :as => "popup_show_lre"
    resources :lres
    match "/posts/popup_show_posts" => "posts#popup_show_post", :as => "popup_show_post"
    resources :posts
    match "/slideshows/popup_show_slideshows" => "slideshows#popup_show_slideshow", :as => "popup_show_slideshow"
    resources :slideshows
    match "/biographies/popup_show_biographies" => "biographies#popup_show_biography", :as => "popup_show_biography"
    resources :biographies
    match "/documents/popup_show_documents" => "documents#popup_show_document", :as => "popup_show_document"
    resources :documents   
    match "/participants/popup_show_participants" => "forms#popup_show_participant", :as => "popup_show_participant"
    resources :participants   
    match "/reports/popup_show_reports" => "reports#popup_show_report", :as => "popup_show_report"
    match "/reports/load_more_reports_by_section_and_date" => "reports#load_more_reports_by_section_and_date" , :as => "load_more_reports_by_section_and_date"
    match "/reports/index_all" => "reports#index_all", :as => "index_all_reports"
    resources :reports
    match "/widgets/popup_show_reports" => "widgets#popup_show_widget", :as => "popup_show_widget"
    resources :widgets
    match "/klascements/popup_show_klascements" => "klascements#popup_show_klascement", :as => "popup_show_klascement"
    resources :klascements
    match "/artworks/popup_show_artworks" => "artworks#popup_show_artwork", :as => "popup_show_artwork"
    resources :artworks
    match "/reuters_new_items/popup_show_reuters_new_items" => "reuters_new_items#popup_show_reuters_new_item", :as => "popup_show_reuters_new_item"
    resources :reuters_new_items    
    match "/books/popup_show_books" => "books#popup_show_book", :as => "popup_show_book"
    resources :books    
    resources :administrations
    match "/sources/popup_show_sources" => "sources#popup_show_source", :as => "popup_show_source"
    resources :sources
    match "/contents/popup_show_content" => "contents#popup_show_content", :as => "popup_show_content"
    resources :contents
    resources :pictures
  
    match "/groups/popup_show_group" => "groups#popup_show_group", :as => "popup_show_group"
    match "/groups/my_groups" => "groups#my_groups" , :as => "my_groups"
    resources :groups    
    
    match "/comments/new" => "comments#new", :as => "new_comment"
    match "/selectors/paginate_elements" => "selectors#paginate_elements"
    
    match 'home' => 'home#index', as: :user_root
    
    match 'about/faqs' => 'about#faqs', as: :about_faqs
    match 'about/about_us' => 'about#about_us', as: :about_about_us

app/models/content.rb
class Content < ActiveRecord::Base
  include Taggable
  include Ownable
  
  translates :name, :description
  
  searchable do
    I18n.available_locales.each do |locale|
      text "name_" + locale.to_s do
        read_attribute(:name, :locale => locale.to_s)
      end
      text "description_" + locale.to_s do
        read_attribute(:description, :locale => locale.to_s)
      end
    end
    
    integer :owner_id
    time :updated_at
  end
  
  belongs_to :subject
  has_many :comments, :as => :commentable, :dependent => :destroy
  
  has_many :content_concrete_requirement_content_annotations
  has_many :content_concrete_requirement_content_assignments
  
  attr_accessible :element_image, :name, :description, :curriculum_topic, :url, :subject_id
  
  has_attached_file :element_image, :styles => { :original => "300x300>", :medium => "200x200>", :thumb => "30x30>" }, :default_url => "none"
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  def index
     @resource_type = "Content" 
    @search = Content.search do
      fulltext params[:search]
      order_by :updated_at, :desc
      paginate :page => params[:page], :per_page => 25
    end
    @contents = @search.results

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.find(params[:id])
    
    if notice == 'Content was successfully created.' || notice == 'Content was successfully updated.'
      @previous_action = 'saved'
    else
      @previous_action = 'list'
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])
    @content.owner = current_user
    @content.creator = current_user
    @content.save
    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Content was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, notice: 'Content was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :ok }
    end
  end
  
  def popup_show_content
    @content = Content.find(params[:element_id])
     
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<%= form_for(@content, :html => { :class => "content" }) do |fo| %>
	<%= render :partial => "contents/form" , :locals => {:content_form => fo} %>
<% end %>
<input type="hidden" id="edition_mode" value="off"/>

app/views/contents/_content_actions.html.erb
<% if @previous_action == "list" %>
	<%=link_to  "javascript: history.back();", :class => "back_icon has_tooltip" do %>
		 <%= image_tag("/images/icons/atras_30.png") %>
		<span class="tooltip"><%= t("Back_to_list")%></span>
	<% end %>
<% else %>
	<%=link_to  contents_path, :class => "back_icon has_tooltip" do %>
		 <%= image_tag("/images/icons/atras_30.png") %>
		<span class="tooltip"><%= t("Back_to_list")%></span>
	<% end %>
<% end %>

<%=link_to edit_content_path(@content), :class => "has_tooltip" do %>
	 <%= image_tag("/images/icons/edit-white.png") %>
	<span class="tooltip"><%= t("Edit")%></span>
<% end %>
<%=link_to  @content, confirm: t('Are_you_sure'), method: :delete, :class => "has_tooltip" do %>
	 <%= image_tag("/images/icons/delete.png") %>
	<span class="tooltip"><%= t("Delete")%></span>
<% end %>

app/views/contents/_form.html.erb
  <%
  @subjects = Subject.all
  %>
  
  <% if @content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
      <% @content.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="content_name editable active">
		<%= content_form.text_field :name, :class => "element_title", :placeholder => t("title") %>
		<i class="icon-pencil icon-grey"></i>
	</div>
		
	<div class= "description_container">
		<div class="content_image picture_container image ">
			<div class="editable active">
				<% if @content.element_image.url() != "none" %>
				<%= image_tag @content.element_image.url(), width:'100%', :class => "image_preview" %>
				<% else %>
				<img class="image_preview" width="100%"/>
				<% end %>
				<div class= "file_upload">
					<%= content_form.file_field :element_image, :onchange => "image_preview(this, event);", :class =>"input_element_image" %>
				</div>
			</div>
		</div>
		<% if @content.element_image.url() != "none" %>
		<div class="content_description editable active description description_right">
		<% else %>
		<div class="content_description editable active description">
		<% end %>
			<textarea id="content_description" name="content[description]" placeholder="<%= t("Description") %>"><%= @content.description %></textarea>
			<i class="icon-pencil icon-grey"></i>
		</div>
		<div class="clear"></div>
		<div class= "select_element_picture_button has_edition_controls active">
			<button onclick= "select_element_picture(this); return false;" class="edition_control"><%= t("Select_picture") %></button>
		</div>
	</div>
	<div class="clear"></div>
	
	<hr />
	<div class="field editable active">
		<p class= "field_label"><%= t("Subject") %>:</p>
		<div style="position: relative;float: left">
			<% if(@content.subject != nil ) %>
			<div class="selector_input">
				<span><%= @content.subject.name %></span>
				<%= select_tag "content[subject_id]", options_from_collection_for_select(@subjects, "id", "name", @content.subject.id), :prompt => "", :class => "edition_control" %>
			</div>
			<% else %>
			<div class="selector_input">
				<span></span>
				<%= select_tag "content[subject_id]", options_from_collection_for_select(@subjects, "id", "name"),  :prompt => "", :class => "edition_control" %>
			</div>
			<% end %>
		</div>
	</div>
	
	<div class="field editable active">
	    <p class= "field_label"><%= t("Curriculum_topic") %>:</p>
	    <div style="position: relative;float: left; width: 80%;">
		    <%= content_form.text_field :curriculum_topic %>
		    <i class="icon-pencil icon-grey"></i>
		</div>
	</div>
	
	<div class="field editable active">
	    <p class= "field_label"><%= t("url") %>:</p>
	    <div class="url_editor" style="position: relative;float: left; width: 80%;">
	    	<span><a href="<%= @content.url %>" target="_blank"><%= @content.url %></a></span>
		    <%= content_form.text_field :url %>
		    <i class="icon-pencil icon-grey"></i>
		</div>
	</div>	
  	

app/views/contents/_form_actions.html.erb
<%=link_to  contents_path, :class => "back_icon has_tooltip" do %>
	 <%= image_tag("/images/icons/atras_30.png") %>
	<span class="tooltip"><p><%= t("Back_to_list")%></p></span>
<% end %>
<%=link_to "", :class => "has_tooltip", :onclick => "save_content_form();return false;" do %>
	 <%= image_tag("/images/icons/save.png") %>
	<span class="tooltip"><p><%= t("Save")%></p></span>
<% end %>

app/views/contents/_header.html.erb
<div id="nav_bar">
			<ul>
				<li class="active resources_link"><%= link_to t("Resources"), resources_path %></li>
				<li class="activities_link"><%= link_to t("activities"), activities_path %></li>
				<li class="activity_sequence_link"><%= link_to t("sequences"), activity_sequences_path %></li>
				<li class="guides_link"><%= link_to t("guides"), guides_path %></li>
				<li class="experiences_link"><a href="#"><%=t :experiences %></a></li>
				<li class="shareboards_link"><%= link_to t("boards") %></li>
			</ul>
		</div>
	</div>
	<div id="section_header" class="resource_header">
		<div id="actions" class="a-left">
			<%= render actions %>
		</div>
		<div id="section_title" class="a-right">
			<p><%= section_title %></p>
		</div>		
	</div>
</header><!-- HEADER -->

app/views/contents/_list.html.erb
<div class= "paginate_controls">
	<%= paginate @contents %>
</div>

<% @contents.each do |content| %>
	<%= render :partial => "elements/element", :locals => {:element => content, :current_layout => current_layout} %>
<% end %>

app/views/contents/_popup_list_actions.html.erb
<div class= "my_activities_filter disabled" onclick="all_users_popup_filter(this);"><%= t("contents") %></div>
<div class= "my_activities_filter" onclick="current_user_popup_filter(this);"><%= t("My_contents") %></div>
<div class="current_user_input_copy_container">
	<%= hidden_field_tag :user_id, current_user.id , :class => 'current_user_id' %>
</div>

<%= form_tag({:action => 'paginate_elements', :controller => 'selectors', :element_class => 'content_requirement_selection', :refresh_popup => 'true'}, :class => "search_form", :method => :get, remote: true) do %>
	<%= text_field_tag :search, params[:search], placeholder: t('Enter_search_term') %>
	<div class="search_button" onclick='$("#content_requirement_selection .search_form").submit()'></div>
	<div class="current_user_input_container"></div>
<% end %>

app/views/contents/_submit.html.erb
<div class="guide_form_actions form_actions">
	<%= content_form.submit t("save"), :class => 'guide_save' %>
</div>	

app/views/contents/edit.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :editing_content), :actions => "form_actions"} %>

<div id="content_container" class="external_content_container">
	<input type="hidden" id="edition_mode" value="on">
	<%= form_for(@content, :html => { :class => "content_form" }) do |f_content| %>
		<%= render :partial => "form" , :locals => {:content_form => f_content} %>
		<%= render :partial => "submit", :locals => {:content_form => f_content} %>
	<% end %>
</div>	

<script src="/javascript/contents_form.js"></script>

app/views/contents/index.html.erb
<%= render :partial => "header", :locals => {:section_title => (t ("Contents")), :actions => "resources/list_actions"} %>

<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'Contents', :actions => "resources/list_actions"} %>
<% end -%>
		
<% content_for :content do %>
<div id="content_index">	
	<%= render :partial => "list", :locals => { :current_layout => "application" }%>
</div> <!-- CONTENT -->

<script src="/javascript/resource_index.js"></script>
<% end -%>

app/views/contents/new.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :new_content), :actions => "form_actions"} %>

<div id="content_container" class="external_content_container">
	<input type="hidden" id="edition_mode" value="on">
	<%= form_for(@content, :html => { :class => "content_form" }) do |f_content| %>
		<%= render :partial => "form" , :locals => {:content_form => f_content} %>
		<%= render :partial => "submit", :locals => {:content_form => f_content} %>
	<% end %>
</div>	

<script src="/javascript/contents_form.js"></script>

app/views/contents/popup_show_content.js.erb
var details = ("<div id='content_container' class='external_content_container'><%=j render :partial => 'contents/content' %></div>");

app/views/contents/show.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :external_content), :actions => "content_actions"} %>

<div id="content_container" class="external_content_container">
	<%= render "content" %>	
</div>

<script src="/javascript/contents_form.js"></script>