config/routes.rb
AREAV03::Application.routes.draw do


  root :to => "public#index"
  
  scope "(/:locale)", :locale => /en|es|pt|lt|no|tr|fr|nl|gl|sk|hu|fi|it/ do
    
    devise_for :users, :controllers => {:registrations => "registrations"}
    match "/activities/filter/:tag_id" => "activities#filter", :as => "activities_filter"
    match "/activities/interaction_filter/:interaction_id" => "activities#filter_by_interaction", :as => "activities_filter_by_interaction"
    match "/activities/my_activities" => "activities#my_activities" , :as => "my_activities"
    match "/activities/pick_it" => "activities#pick_it" , :as => "pick_it"
    match "/activities/new/from_template/:template_id" => "activities#new", :as => "new_activity_with_template"
    match "/activities/popup_show_activity" => "activities#popup_show_activity" , :as => "popup_show_activity"
    match "/activities/search" => "activities#search", :as => "search"
    resources :activities
    
    match "/scenarios/pick_it" => "scenarios#pick_it" , :as => "pick_it"
    match "/scenarios/my_scenarios" => "scenarios#my_scenarios" , :as => "my_scenarios"
    resources :scenarios
    
    
    match "/bookmarks/add_bookmark" => "bookmarks#add_bookmark"
    match "/bookmarks/remove_bookmark" => "bookmarks#remove_bookmark"
    resources :bookmarks
        
    resources :created_elements
    
    match "/search_results/all_related_elements" => "search_results#all_related_elements" , :as => "all_related_elements"
    match "/search_results/all_best_search_results" => "search_results#all_best_search_results" , :as => "all_best_search_results"
    match "/search_results/load_more_search_results" => "search_results#load_more_search_results" , :as => "load_more_search_results"
    match "/search_results/load_more_related_elements" => "search_results#load_more_related_elements" , :as => "load_more_related_elements"
    resources :search_results
        
    resources :requirements
    match "/activity_sequences/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/:activity_sequence_id/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/new_activity_instance" => "activity_sequences#new_activity_instance"
    match "/activity_sequences/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/:activity_sequence_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/my_activity_sequences" => "activity_sequences#my_activity_sequences" , :as => "my_activity_sequences"
    match "/activity_sequences/pick_it" => "activity_sequences#pick_it" , :as => "pick_it"
    match "/activity_sequences/get_activity" => "activity_sequences#get_activity" , :as => "get_activity"
    match "/activity_sequences/popup_show_activity_sequence" => "activity_sequences#popup_show_activity_sequence" , :as => "popup_show_activity_sequence"
    resources :activity_sequences
    
    match "/guides/show_activity" => "activity_sequences#show_activity"
    match "/guides/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/show_sequence" => "guides#show_sequence"
    match "/guides/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/select_sequence" => "guides#select_sequence"
    match "/guides/get_sequence" => "guides#get_sequence"
    match "/guides/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/new_sequence" => "guides#new_sequence"
    match "/guides/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/recommend_tools" => "guides#recommend_tools"
    match "/guides/recommend_people" => "guides#recommend_people"
    match "/guides/recommend_events" => "guides#recommend_events"
    match "/guides/popup_show_guide" => "guides#popup_show_guide", :as => "popup_show_guide"
    match "/guides/my_guides" => "guides#my_guides" , :as => "my_guides"
    match "/guides/pick_it" => "guides#pick_it" , :as => "pick_it"
    match "/guides/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    match "/guides/:guide_id/show_activity" => "activity_sequences#show_activity"
    match "/guides/:guide_id/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/:guide_id/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/:guide_id/show_sequence" => "guides#show_sequence"
    match "/guides/:guide_id/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/:guide_id/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/:guide_id/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/:guide_id/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/:guide_id/select_sequence" => "guides#select_sequence"
    match "/guides/:guide_id/get_sequence" => "guides#get_sequence"
    match "/guides/:guide_id/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/:guide_id/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/:guide_id/new_sequence" => "guides#new_sequence"
    match "/guides/:guide_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/:guide_id/recommend_tools" => "guides#recommend_tools"
    match "/guides/:guide_id/recommend_people" => "guides#recommend_people"
    match "/guides/:guide_id/recommend_events" => "guides#recommend_events"
    match "/guides/:guide_id/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    resources :guides
    match "/technological_settings/popup_show_technological_setting" => "technological_settings#popup_show_technological_setting" , :as => "popup_show_technological_setting"
    resources :technological_settings
    match "/contextual_settings/popup_show_contextual_setting" => "contextual_settings#popup_show_contextual_setting" , :as => "popup_show_contextual_setting"
    resources :contextual_settings
    resources :seeds

    match "/experiences/popup_show_experience" => "experiences#popup_show_experience", :as => "popup_show_experience"
    match "/experiences/new/from_guide/:guide_id" => "experiences#new", :as => "new_experience_from_guide"
    match "/experiences/my_experiences" => "experiences#my_experiences" , :as => "my_experiences"
    match "/experiences/get_element_excerpt" => "experiences#get_element_excerpt"    
    resources :experiences

    
    match "/users/popup_show_user" => "users#popup_show_user", :as => "popup_show_user"
    resources :users    
    match "/resources/list_devices" => "resources#list_devices" , :as => "list_devices"
    match "/resources/list_applications" => "resources#list_applications" , :as => "list_applications"
    match "/resources/list_people" => "resources#list_people" , :as => "list_people"
    match "/resources/list_events" => "resources#list_events" , :as => "list_events"            
    resources :resources
    match "/devices/popup_show_device" => "devices#popup_show_device", :as => "popup_show_device"
    resources :devices
    match "/applications/popup_show_application" => "applications#popup_show_application", :as => "popup_show_application"
    resources :applications
    match "/people/popup_show_person" => "people#popup_show_person", :as => "popup_show_person"
    resources :people
    match "/events/popup_show_event" => "events#popup_show_event", :as => "popup_show_event"
    resources :events
    match "/lectures/popup_show_lecture" => "lectures#popup_show_lecture", :as => "popup_show_lecture"
    resources :lectures
    match "/sites/popup_show_site" => "sites#popup_show_site", :as => "popup_show_site"
    resources :sites
    match "/documentaries/popup_show_documentary" => "documentaries#popup_show_documentary", :as => "popup_show_documentary"
    resources :documentaries
    match "/courses/popup_show_course" => "courses#popup_show_course", :as => "popup_show_course"
    resources :courses
    match "/articles/popup_show_article" => "articles#popup_show_article", :as => "popup_show_article"
    resources :articles
    match "/lres/popup_show_lre" => "lres#popup_show_lre", :as => "popup_show_lre"
    resources :lres
    match "/posts/popup_show_posts" => "posts#popup_show_post", :as => "popup_show_post"
    resources :posts
    match "/slideshows/popup_show_slideshows" => "slideshows#popup_show_slideshow", :as => "popup_show_slideshow"
    resources :slideshows
    match "/biographies/popup_show_biographies" => "biographies#popup_show_biography", :as => "popup_show_biography"
    resources :biographies
    match "/documents/popup_show_documents" => "documents#popup_show_document", :as => "popup_show_document"
    resources :documents   
    match "/participants/popup_show_participants" => "forms#popup_show_participant", :as => "popup_show_participant"
    resources :participants   
    match "/reports/popup_show_reports" => "reports#popup_show_report", :as => "popup_show_report"
    match "/reports/load_more_reports_by_section_and_date" => "reports#load_more_reports_by_section_and_date" , :as => "load_more_reports_by_section_and_date"
    match "/reports/index_all" => "reports#index_all", :as => "index_all_reports"
    resources :reports
    match "/widgets/popup_show_reports" => "widgets#popup_show_widget", :as => "popup_show_widget"
    resources :widgets

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery
  #before_filter :authenticate_user!
  # Pass the locale as a URL query parameter
  layout :resolve_layout
  before_filter :set_locale
  #before_filter :authenticate_user!, :except => [:index]
  # before_filter :authenticate_user! 
   
  def extract_locale_from_accept_language_header
    browser_language = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    accepted_languages =["en","es","pt","lt","no","tr","fr","nl","gl","sk","hu","fi"]
    if accepted_languages.include? browser_language
       return browser_language
    else
       return nil
    end 
  end
  
  def set_locale     
    I18n.locale = params[:locale] || extract_locale_from_accept_language_header || I18n.default_locale
  end
    
  
  # Every helper method will include the URL in the query string
  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    { :locale => I18n.locale }
  end
  
  def self.default_url_options
  { :locale => I18n.locale }
  end

  def resolve_layout
    case action_name
    when "new", "create"
      "application"
    when "index","my_groups", "all_related_elements", "index_all"
      "listing"
    else
      "application"
    end
  end
  
  
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/_advanced_search.html.erb
<% if @previous_search_params != nil && @previous_search_params[:advanced_search] == "1" %>
<div class="advanced_search row-fluid visible">
<% else %>
<div class="advanced_search row-fluid">
<% end %>
	<div class="span12 advanced_search_padding">
		
		<form class="advanced_search_form" id="advanced_search_form">
			<div class="row-fuid">
				<div class="span3">			
						<div class="field_label c_white"><%= t('functionality') %></div>
						<% if @previous_search_params[:functionality]!=nil && @previous_search_params[:functionality]!="" %>
							<div><%= select_tag "functionality", options_from_collection_for_select(@funtionalities, "id", "name",@previous_search_params[:functionality]), :prompt => "", :class => "edition_control subject" %></div>
						<% else %>
							<div><%= select_tag "functionality", options_from_collection_for_select(@funtionalities, "id", "name"), :prompt => "", :class => "edition_control subject" %></div>
						<% end %>
						<div class="field_label c_white"><%= t('search_terms') %></div>
						<div>
							<% if @previous_search_params[:search]!=nil && @previous_search_params[:search]!="" %>
								<input type="text" name="search" id="search" value="<%=@previous_search_params[:search]%>"/>
							<% else %>
								<input type="text" name="search" id="search"/>
							<% end %>	
						</div>						
				</div>
				<div class="span2">						
					<div style="margin-top:15px;">
						<!--													
						<% if @previous_search_params[:enriched]!=nil && @previous_search_params[:enriched]!="" && @previous_search_params[:enriched]!="1"%>	
							<button class="button_advanced_search field_label" id="enriched_button" onclick="toogle_enriched_advanced_search(event);"><%= t('enriched_off') %></button>
							<input type="hidden" id="enriched" name="enriched" value="0"/>												
						<% else %>
							<button class="button_advanced_search field_label active" id="enriched_button" onclick="toogle_enriched_advanced_search(event);"><%= t('enriched_on') %></button>
							<input type="hidden" id="enriched" name="enriched" value="1"/>
						<% end %>
						-->
					</div>
					
					<div style="margin-top:60px;">
						<button class="button_advanced_search field_label" id="search_button" onclick="submit_advanced_search(event);"><%= t('search') %></button>
						<input type="hidden" id="advanced_search" name="advanced_search" value="0">
					</div>
					
				</div>
				<div class="span4">
								
				</div>
				<div class="span3">
					<div class="row-fluid" style="height: 100px;">
						<div class="span11 num_results_advanced_search c_white"><%= t('results') %>:&nbsp;<span id="num_results"></span><%=@num_results%></div>
						<div class="span11 title_advanced_search c_white" style="margin-top: 20px;"><%= t("search") %> </div>
						<div class="span11 description_advanced_search c_white"><%= t('fill_inputs_and_search') %></div>
						<div class="clear"></div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>		

app/views/applications/_application.html.erb
<%= form_for(@application, :html => { :class => "application_form" }) do |fo| %>
	<%= render :partial => "applications/form" , :locals => {:application_form => fo} %>
<% end %>
<input type="hidden" id="edition_mode" value="off"/>

app/views/applications/_application_actions.html.erb
<li>
<% if @previous_action == "list" %>
	<%=link_to  "javascript: history.back();", :class => "back_icon has_tooltip" do %>
	 	 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
	<% end %>
<% else %>
	<%=link_to  applications_path, :class => "back_icon has_tooltip" do %>
	 	 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
	<% end %>
<% end %>
</li>

<% if current_user != nil && ((@application.owner == current_user) or (@application.owner_type=="Group" && @application.owner.users.exists?(current_user))) %>
	<li>
	<%=link_to edit_application_path(@application), :class => "has_tooltip" do %>
		 <img src="/images/white_edit.png" title="<%= t('edit') %>"></img>
	<% end %>
	</li>
	<li>
	<%=link_to  @application, confirm: t('are_you_sure'), method: :delete, :class => "has_tooltip" do %>
		 <img src="/images/white_delete.png" title="<%= t('delete') %>"></img>
	<% end %>	
	</li>
<% end %>

<li>
	<%= form_tag search_results_path, :method => 'get' do %>  
    	<%= text_field_tag :search, params[:search], :class => "subnavbar_search" %>&nbsp;&nbsp;<%= submit_tag t('search'),:class => "search_button_subnavbar" %>  
	<% end %>
</li>

app/views/applications/_form.html.erb
<% if @application.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>
	
	  <ul>
	  <% @application.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<% end %>



<!------------ Left column ------------------>
<div class="left_column">
	<div class="application_name field_body">
		<% if @edition_mode==true %>
			<textarea id="application_name" name="application[name]" placeholder="<%= t("title") %>"><%= @application.name %></textarea>
			<i class="icon-pencil icon-grey"></i>
		<% else %>
			<span><%= @application.name %></span>
		<% end %>
	</div>
	
		
	<div class="application_description description field_body">
		<% if @edition_mode==true %>
			<textarea id="application_description" name="application[description]" placeholder="<%= t("description") %>"><%= @application.description %></textarea>
			<i class="icon-pencil icon-grey"></i>
		<% else %>
			<div>
				<% if @application.description != nil %>			
					<%= raw @application.description.truncate(1000, :separator => " ", :omission => "...") %>
				<% end %>				
			</div>
		<% end %>
	</div>
	
	
	<div class="application_tags element_field_box">
		<div class="field_prompt"><%= t("keywords") %></div>
		<div class="field_body">			
			<% if @edition_mode==true %>    
		    	<textarea id="application_tags" class="tags" name="application[tag_list]"><% if @application!=nil %><%= @application.tag_list %><% end %></textarea>
		    	<i class="icon-pencil icon-grey"></i>
		    <% else %>
		    	<span class="tags"><% if @application!=nil %><%= @application.tag_list_with_links.html_safe %><% end %></span>	
		    <% end %>														
		</div>
	</div>		
	
	
	<div class="application_url element_field_box">
		<div class="field_prompt"><%= t("url") %></div>
		<div class="field_body">
			<% if @edition_mode==true %>    
		    	<%= application_form.text_field :url %>
		    	<i class="icon-pencil icon-grey"></i>			    	
		    <% else %>
		    	<a href="<%= @application.url %>" target="_blank"><%= @application.url %></a>
		    <% end %>
	   </div>		
	</div>

	<% if @edition_mode == true or @application.application_operating_system_annotations.size > 0 %>
	<div class="application_operating_systems element_field_box">
		<div class="field_prompt"><%= t("operating_systems") %></div>
		<div class="field_body">
			<% if @edition_mode==true %>
				<% @application.application_operating_system_annotations.each do |annotation| %>
					<div class="operating_system_item">
						<%= select_tag "operating_system", options_from_collection_for_select(@operating_systems, "id", "name", annotation.operating_system.id), :prompt => "", :class => "operating_system" %>
						<span class="delete_operating_system"  onClick="delete_operating_system(this);">X</span>					
					</div>
				<% end %>
			<% else %>
				<div><span>
					<% @application.application_operating_system_annotations.each do |annotation| %>
						<%= annotation.operating_system.name %>&nbsp;
					<% end %>
				</div></span>
			<% end %>			
		</div>
		<% if @edition_mode==true %>
			<div class="add_item_to_itemize" onclick="add_operating_system(this);">
				<span>+</span>
			</div>
		<% end %>		
	</div>
	<% end %>


	<% if @edition_mode == true or @application.application_functionality_annotations.size > 0 %>
	<div class="application_functionalities element_field_box">
		<div class="field_prompt"><%= t("functionalities") %></div>
		<div class="field_body">			
			<% @application.application_functionality_annotations.each do |annotation| %>						
				<div class="selector_with_slider">
					<div class="selector_field">
						<% if @edition_mode==true %>
							<%= select_tag "functionality", options_from_collection_for_select(@functionalities, "id", "name", annotation.functionality.id), :prompt => "", :class => "functionality" %>						
						<% else %>
							<span><%= annotation.functionality.name %></span>
						<% end %>
					</div>
					<div class="slider_with_input">
						<div class="input_field">					
							<% if @edition_mode==true %>
								<input type="text" class="level" value="<%= annotation.level%>" />
							<% else %>
								<span><%= t("level") %>:&nbsp;<%= annotation.level%></span>								
							<% end %>
						</div>
						<% if @edition_mode==true %>
							<div class="slider"></div>
						<% end %>
					</div>
					<% if @edition_mode==true %>
						<div class="delete_selector_with_slider"  onClick="delete_selector_with_slider(this);">x</div>
					<% end %>		
					<div class="clear"></div>															
				</div>				
			<% end %>						
		</div>
		<% if @edition_mode==true %>			
			<div class="add_item_to_itemize">
				<span onclick="add_selector_with_slider(this);">+</span>
			</div>			
		<% end %>
	</div>
	<% end %>



	<% if @edition_mode!=true && @application.scraped_from!=nil && @application.scraped_from!="" %>  
		<div class="application_scraped_from element_field_box">
			<div class="field_prompt"><%= t("source") %></div>
			<div class="field_body">
				<a href="<%= @application.scraped_from %>" target="_blank"><%= @application.scraped_from %></a>
			</div>
		</div>
	<% end %>

</div>



<!------------- Right column ---------------->
<div class="right_column">
	<% if @edition_mode == false && @popup == nil %>	
		<div class="watermark_container_show">
			<div class="watermark_show <%=@resource_type.downcase%>_watermark"></div>
		</div>
	<% end %>
	<div class="element_image_box picture_container">
		<% if @edition_mode==true %>	
			<span class="change_element_image has_edition_controls active" onclick= "select_element_image_new(this);"><%= t('change_image') %></span>		
			<% if @application.element_image.url() != "none" %>
				<%= image_tag @application.element_image.url(:medium), width:'100%', :class => "image_preview" %>
			<% else %>
				<%= image_tag "/images/watermarks/b_watermark_application.png", width:'100%', :class => "image_preview" %>
			<% end %>
			<div class= "file_upload">
				<%= application_form.file_field :element_image, :onchange => "image_preview_new(this, event);", :class =>"input_element_image" %>
			</div>
		<% else %>
			<% if @application.element_image.url() != "none" %>
				<%= image_tag @application.element_image.url(:medium), width:'100%', :class => "image_preview_show" %>
			<% else %>
				<%= image_tag "/images/no_photo.png", width:'100%', :class => "image_preview_show" %>
			<% end %>
		<% end %>
	</div>
</div>






<% if @edition_mode==true %>
	<div id="snippets_library" style="display: none">				
		<div class="selector_with_slider">
			<div class="selector_field">				
				<%= select_tag "functionality", options_from_collection_for_select(@functionalities, "id", "name"),  :prompt => "", :class => "edition_control functionality" %>
			</div>
			<div class="slider_with_input">
				<div class="input_field">					
					<input type="text" class="level" style="border: 0; color: #f6931f; font-weight: bold;" />
				</div>
				<div class="slider"></div>													
			</div>			
			<div class="delete_selector_with_slider"  onClick="delete_selector_with_slider(this);">x</div>		
			<div class="clear"></div>
		</div>
		
		
		<div class="operating_system_item">			
			<%= select_tag "operating_system", options_from_collection_for_select(@operating_systems, "id", "name"), :prompt => "", :class => "operating_system" %>
			<span class="delete_operating_system"  onClick="delete_operating_system(this);">X</span>			
		</div>		
	</div>
<% end %>
						

app/views/applications/_form_actions.html.erb
<li>
<%=link_to  applications_path, :class => "back_icon has_tooltip" do %>
	 	 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
<% end %>
</li>
<li>
<%=link_to "", :class => "has_tooltip", :onclick => "save_application_form();return false;" do %>
	 	 <img src="/images/white_save.png" title="<%= t('save') %>"></img>
<% end %>
</li>

app/views/applications/_header.html.erb
<div id="section_header" class="resource_header">
	<div id="actions" class="a-left">
		<%= render actions %>
	</div>
	<div id="section_title" class="a-right">
		<p><%= section_title %></p>
	</div>		
</div>

app/views/applications/_list.html.erb
<% if @num_results == 0 %>
	<div class="no_results"><%= t('no_results')%></div>			
<% end %>

<% @applications.each do |application| %>
	<%= render :partial => "elements/element_fixed", :locals => {:element => application, :current_layout => current_layout} %>
<% end %>

<div class="clear"></div>

<div class= "paginate_controls active">
	<%= paginate @applications %>
</div>

app/views/applications/_popup_list_actions.html.erb
<div class= "my_activities_filter disabled" onclick="all_users_popup_filter(this);"><%= t("applications") %></div>
<div class= "my_activities_filter" onclick="current_user_popup_filter(this);"><%= t("my_applications") %></div>
<div class= "my_activities_filter" onclick="bookmarks_current_user_popup_filter(this)"><%= t("bookmarked_applications") %></div>
<div class="current_user_input_copy_container">
	<%= hidden_field_tag :user_id, current_user.id , :class => 'current_user_id' %>	
</div>
<div class="bookmarks_input_copy_container" >
	<%= hidden_field_tag :display_bookmarks, "true", :class => 'display_bookmarks' %>
</div>

<%= form_tag({:action => 'paginate_elements', :controller => 'selectors', :element_class => 'tool_assignment_selection', :refresh_popup => 'true'}, :class => "search_form", :method => :get, remote: true) do %>
	<%= text_field_tag :search, params[:search], placeholder: t('enter_search_term') %>
	<div class="search_button" onclick='$("#technological_setting_application_selection .search_form").submit()'></div>
	<div class="current_user_input_container"></div>
<% end %>

app/views/applications/_submit.html.erb
<div class="application_form_actions form_actions">
	<%= application_form.submit t("save"), :class => 'application_save' %>
</div>	

app/views/applications/edit.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :Editing_application), :actions => "form_actions"} %>

<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'editing_application', :actions => "applications/form_actions"} %>
<% end %>

<% content_for :content do %>
	<%= form_for(@application, :html => { :class => "application_form" }) do |f_application| %>
		<div id="element_header">
			<%= render :partial => "generic_partials/ownership_group_small" , :locals => {:edition_mode => @edition_mode,:element => @application,:element_type=>"application"} %> 
			<hr />
			<div class="clear"></div>
		</div>
	
		<div id="content_container" class="application_container">
			<input type="hidden" id="edition_mode" value="on">		
				<%= render :partial => "form" , :locals => {:application_form => f_application} %>
				<%= render :partial => "submit", :locals => {:application_form => f_application} %>
		</div>	
	<% end %>
	<span style="display:none" id="is_edition" data-value="true"></span>
		
	<script src="/javascript/applications_form.js"></script>
<% end %>

app/views/applications/index.html.erb
<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'applications', :actions => "resources/list_actions"} %>
<% end -%>


<% content_for :advanced_search do %>	
	<%= render :partial =>"advanced_search" %>
<% end %>


<% content_for :content do %>
	<div class="content_disambiguation">
		<%= render :partial => "generic_partials/resource_disambiguation" %>
	</div>
	<div id="content_index">
		<%= render :partial => "list", :locals => { :current_layout => "application" }%>
	</div> <!-- CONTENT -->
	
	<script src="/javascript/resource_index.js"></script>
	<script src="/javascript/applications_index.js"></script>

<% end %>

app/views/applications/index.js.erb
jQuery("#content_index").append(<% @applications.each do |application| %><%= escape_javascript(render :partial => "elements/element", :locals => {:element => application, :current_layout => current_layout}) 

app/views/applications/new.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :new_application), :actions => "form_actions"} %>

<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'new_application', :actions => "applications/form_actions"} %>
<% end %>

<% content_for :content do %>
	<%= form_for(@application, :html => { :class => "application_form" }) do |f_application| %>
		<div id="element_header">
			<%= render :partial => "generic_partials/ownership_group_small" , :locals => {:edition_mode => @edition_mode,:element => @application,:element_type=>"application"} %> 
			<hr />
			<div class="clear"></div>
		</div>
	
		<div id="content_container" class="application_container">
			<input type="hidden" id="edition_mode" value="on">
				<%= render :partial => "form" , :locals => {:application_form => f_application} %>
				<%= render :partial => "submit", :locals => {:application_form => f_application} %>			
		</div>	
	<% end %>
	
	<span style="display:none" id="is_edition" data-value="true"></span>
	<script src="/javascript/applications_form.js"></script>
<% end %>