config/routes.rb
AREAV03::Application.routes.draw do


  root :to => "public#index"
  
  scope "(/:locale)", :locale => /en|es|pt|lt|no|tr|fr|nl|gl|sk|hu|fi|it/ do
    
    devise_for :users, :controllers => {:registrations => "registrations"}
    match "/activities/filter/:tag_id" => "activities#filter", :as => "activities_filter"
    match "/activities/interaction_filter/:interaction_id" => "activities#filter_by_interaction", :as => "activities_filter_by_interaction"
    match "/activities/my_activities" => "activities#my_activities" , :as => "my_activities"
    match "/activities/pick_it" => "activities#pick_it" , :as => "pick_it"
    match "/activities/new/from_template/:template_id" => "activities#new", :as => "new_activity_with_template"
    match "/activities/popup_show_activity" => "activities#popup_show_activity" , :as => "popup_show_activity"
    match "/activities/search" => "activities#search", :as => "search"
    resources :activities
    
    match "/scenarios/pick_it" => "scenarios#pick_it" , :as => "pick_it"
    match "/scenarios/my_scenarios" => "scenarios#my_scenarios" , :as => "my_scenarios"
    resources :scenarios
    
    
    match "/bookmarks/add_bookmark" => "bookmarks#add_bookmark"
    match "/bookmarks/remove_bookmark" => "bookmarks#remove_bookmark"
    resources :bookmarks
        
    resources :created_elements
    
    match "/search_results/all_related_elements" => "search_results#all_related_elements" , :as => "all_related_elements"
    match "/search_results/all_best_search_results" => "search_results#all_best_search_results" , :as => "all_best_search_results"
    match "/search_results/load_more_search_results" => "search_results#load_more_search_results" , :as => "load_more_search_results"
    match "/search_results/load_more_related_elements" => "search_results#load_more_related_elements" , :as => "load_more_related_elements"
    resources :search_results
        
    resources :requirements
    match "/activity_sequences/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/:activity_sequence_id/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/new_activity_instance" => "activity_sequences#new_activity_instance"
    match "/activity_sequences/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/:activity_sequence_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/my_activity_sequences" => "activity_sequences#my_activity_sequences" , :as => "my_activity_sequences"
    match "/activity_sequences/pick_it" => "activity_sequences#pick_it" , :as => "pick_it"
    match "/activity_sequences/get_activity" => "activity_sequences#get_activity" , :as => "get_activity"
    match "/activity_sequences/popup_show_activity_sequence" => "activity_sequences#popup_show_activity_sequence" , :as => "popup_show_activity_sequence"
    resources :activity_sequences
    
    match "/guides/show_activity" => "activity_sequences#show_activity"
    match "/guides/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/show_sequence" => "guides#show_sequence"
    match "/guides/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/select_sequence" => "guides#select_sequence"
    match "/guides/get_sequence" => "guides#get_sequence"
    match "/guides/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/new_sequence" => "guides#new_sequence"
    match "/guides/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/recommend_tools" => "guides#recommend_tools"
    match "/guides/recommend_people" => "guides#recommend_people"
    match "/guides/recommend_events" => "guides#recommend_events"
    match "/guides/popup_show_guide" => "guides#popup_show_guide", :as => "popup_show_guide"
    match "/guides/my_guides" => "guides#my_guides" , :as => "my_guides"
    match "/guides/pick_it" => "guides#pick_it" , :as => "pick_it"
    match "/guides/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    match "/guides/:guide_id/show_activity" => "activity_sequences#show_activity"
    match "/guides/:guide_id/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/:guide_id/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/:guide_id/show_sequence" => "guides#show_sequence"
    match "/guides/:guide_id/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/:guide_id/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/:guide_id/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/:guide_id/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/:guide_id/select_sequence" => "guides#select_sequence"
    match "/guides/:guide_id/get_sequence" => "guides#get_sequence"
    match "/guides/:guide_id/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/:guide_id/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/:guide_id/new_sequence" => "guides#new_sequence"
    match "/guides/:guide_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/:guide_id/recommend_tools" => "guides#recommend_tools"
    match "/guides/:guide_id/recommend_people" => "guides#recommend_people"
    match "/guides/:guide_id/recommend_events" => "guides#recommend_events"
    match "/guides/:guide_id/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    resources :guides
    match "/technological_settings/popup_show_technological_setting" => "technological_settings#popup_show_technological_setting" , :as => "popup_show_technological_setting"
    resources :technological_settings
    match "/contextual_settings/popup_show_contextual_setting" => "contextual_settings#popup_show_contextual_setting" , :as => "popup_show_contextual_setting"
    resources :contextual_settings
    resources :seeds

    match "/experiences/popup_show_experience" => "experiences#popup_show_experience", :as => "popup_show_experience"
    match "/experiences/new/from_guide/:guide_id" => "experiences#new", :as => "new_experience_from_guide"
    match "/experiences/my_experiences" => "experiences#my_experiences" , :as => "my_experiences"
    match "/experiences/get_element_excerpt" => "experiences#get_element_excerpt"    
    resources :experiences

    
    match "/users/popup_show_user" => "users#popup_show_user", :as => "popup_show_user"
    resources :users    
    match "/resources/list_devices" => "resources#list_devices" , :as => "list_devices"
    match "/resources/list_applications" => "resources#list_applications" , :as => "list_applications"
    match "/resources/list_people" => "resources#list_people" , :as => "list_people"
    match "/resources/list_events" => "resources#list_events" , :as => "list_events"            
    resources :resources
    match "/devices/popup_show_device" => "devices#popup_show_device", :as => "popup_show_device"
    resources :devices
    match "/applications/popup_show_application" => "applications#popup_show_application", :as => "popup_show_application"
    resources :applications
    match "/people/popup_show_person" => "people#popup_show_person", :as => "popup_show_person"
    resources :people
    match "/events/popup_show_event" => "events#popup_show_event", :as => "popup_show_event"
    resources :events
    match "/lectures/popup_show_lecture" => "lectures#popup_show_lecture", :as => "popup_show_lecture"
    resources :lectures
    match "/sites/popup_show_site" => "sites#popup_show_site", :as => "popup_show_site"
    resources :sites
    match "/documentaries/popup_show_documentary" => "documentaries#popup_show_documentary", :as => "popup_show_documentary"
    resources :documentaries
    match "/courses/popup_show_course" => "courses#popup_show_course", :as => "popup_show_course"
    resources :courses
    match "/articles/popup_show_article" => "articles#popup_show_article", :as => "popup_show_article"
    resources :articles
    match "/lres/popup_show_lre" => "lres#popup_show_lre", :as => "popup_show_lre"
    resources :lres
    match "/posts/popup_show_posts" => "posts#popup_show_post", :as => "popup_show_post"
    resources :posts
    match "/slideshows/popup_show_slideshows" => "slideshows#popup_show_slideshow", :as => "popup_show_slideshow"
    resources :slideshows
    match "/biographies/popup_show_biographies" => "biographies#popup_show_biography", :as => "popup_show_biography"
    resources :biographies
    match "/documents/popup_show_documents" => "documents#popup_show_document", :as => "popup_show_document"
    resources :documents   
    match "/participants/popup_show_participants" => "forms#popup_show_participant", :as => "popup_show_participant"
    resources :participants   
    match "/reports/popup_show_reports" => "reports#popup_show_report", :as => "popup_show_report"
    match "/reports/load_more_reports_by_section_and_date" => "reports#load_more_reports_by_section_and_date" , :as => "load_more_reports_by_section_and_date"
    match "/reports/index_all" => "reports#index_all", :as => "index_all_reports"
    resources :reports
    match "/widgets/popup_show_reports" => "widgets#popup_show_widget", :as => "popup_show_widget"
    resources :widgets

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  include Taggable
  include Ownable
  include Globalizable
  
  Globalize.fallbacks = {:en => [:en, :fi], :fi => [:fi, :en]}
  
  translates :name, :description
  
  searchable do
    I18n.available_locales.each do |locale|
      text "name_" + locale.to_s do
        read_attribute(:name, :locale => locale.to_s)
      end
      text "description_" + locale.to_s do
        read_attribute(:description, :locale => locale.to_s)
      end
    end    
    integer :owner_id
    time :updated_at
    boolean :template
    
    string :translations, :multiple => true do
      translations.map{|translation| translation.locale}
    end
  end
  
  
  has_many :boxes, :dependent => :destroy, :as => :document
  has_many :comments, :as => :commentable, :dependent => :destroy

  accepts_nested_attributes_for :boxes, :allow_destroy => :true
  
  attr_accessible :element_image, :name, :description, :boxes_attributes, :owner_id, :owner_type
  has_attached_file :element_image, :styles => { :original => "300x300>", :medium => "200x200>", :thumb => "30x30>" }, :default_url => "none"

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  def index
    @page = "scenarios"
    if I18n.locale.to_s == "gl" 
      search_languages=["gl","es"]
    else 
      search_languages=[I18n.locale.to_s]
    end
    per_page = 32
 
    @search = Scenario.search do
      fulltext params[:search]     
      with :template, nil
      with :translations, search_languages
      order_by :updated_at, :desc
      paginate :page => params[:scenarios_page], :per_page => per_page
    end
    
    @scenarios = @search.results          
    @num_results=@search.total  
     
    
       
    @tags = Tag.find(:all, :order => 'name')
    #@templates = Scenario.find(:all,:conditions => { :template => true }) 
    @previous_search_params=params
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scenarios }
    end
  end
  
  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    @scenario = Scenario.find(params[:id])
    if notice == 'Scenario was successfully created.' || notice == 'Scenario was successfully updated.'
      @previous_action = 'saved'
    else
      @previous_action = 'list'
    end
    @edition_mode=false
        
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scenario }
    end
  end

  def new
    if current_user != nil     
      @scenario_template = Scenario.where(:template => true)[0]
      @scenario = Scenario.new()
      @scenario_template.boxes.each do |box|
        box_clone = box.clone
        @scenario.boxes << box_clone
      end
      @edition_mode=true
       
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @scenario }
      end
    else
      redirect_to scenarios_path
    end
  end


  def edit
    @scenario = Scenario.find(params[:id])
    if current_user !=nil && ((@scenario.owner == current_user) or (@scenario.owner_type=="Group" && @scenario.owner.users.exists?(current_user)))
      @edition_mode=true
    else
      redirect_to scenario_path(@scenario)
    end

  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    @scenario = Scenario.new(params[:scenario])
    if (params[:scenario][:owner_type]==nil)
      @scenario.owner_type="User"
      @scenario.owner=current_user
    end
    @scenario.creator = current_user

    @scenario.save
    @scenario.reload
        
    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.'}
        format.json { render json: @scenario, status: :created, location: @scenario }
      else
        format.html { render action: "new" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @scenario = Scenario.find(params[:id])
    if (params[:scenario][:owner_type]==nil)
      @scenario.owner_type="User"
      @scenario.owner=current_user
    end   
    
    respond_to do |format|
      if @scenario.update_attributes(params[:scenario])
        #@scenario.status = 'class'
        @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.'}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroy
    @scenario = Scenario.find(params[:id])
    @scenario.destroy

    respond_to do |format|
      format.html { redirect_to scenarios_url }
      format.json { head :ok }
    end
  end
  
  
  def popup_show_scenario
    @scenario = Scenario.find(params[:element_id])
   
    respond_to do |format|
      format.js
    end
  end
  
end

app/views/scenarios/_adding_elements.html.erb
<div id="item_to_itemize">
	<div class= "text_container editable active deleteable has_edition_controls">
		<div class="delete_button edition_control" onclick="delete_text_container(this);"><%= image_tag("/images/icons/delete_item.png") %></div>
		<%= hidden_field_tag :text_id,"", :class => "text_id" %>
		<li class="itemize_li"></li>
		<%= text_area_tag "text_content","", :class => "text_content", :placeholder => t("write_here") %>
		<i class="icon-pencil icon-grey"></i>
	</div>		
</div>

app/views/scenarios/_advanced_search.html.erb
<% if @previous_search_params != nil && @previous_search_params[:advanced_search] == "1" %>
<div class="advanced_search row-fluid visible">
<% else %>
<div class="advanced_search row-fluid">
<% end %>
	<div class="span12 advanced_search_padding">
		
		<form class="advanced_search_form" id="advanced_search_form">
			<div class="row-fuid">
				<div class="span3">																			
						<div class="field_label c_white"><%= t('search') %></div>
						<div>
							<% if @previous_search_params[:search]!=nil && @previous_search_params[:search]!="" %>
								<input type="text" name="search" id="keywords" value="<%=@previous_search_params[:search]%>"/>
							<% else %>
								<input type="text" name="search" id="keywords"/>
							<% end %>		
						</div>						
				</div>
				<div class="span2">										
					<div style="margin-top:15px;">
						<button class="button_advanced_search field_label" id="search_button" onclick="submit_advanced_search(event);"><%= t('search') %></button>
						<input type="hidden" id="advanced_search" name="advanced_search" value="0">
					</div>
					
				</div>
				<div class="span4">
															
		
				</div>
				<div class="span3">
					<div class="row-fluid" style="height: 60px;">
						<div class="span11 num_results_advanced_search c_white"><%= t('results')%>:&nbsp;<span id="num_results"></span><%=@num_results%></div>
						<div class="span11 title_advanced_search c_white"  style="margin-top: 10px;"><%= t("search") %> </div>						
						<div class="clear"></div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>		

app/views/scenarios/_form.html.erb
<% if @scenario.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>
	
	  <ul>
	  <% @scenario.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<% end %>

<%= f.hidden_field :id %>
<!-- me cargue el status -->
<!-- f.hidden_field :status, :value => "instance" -->

<div class="scenario_name editable active name">
	<%= f.text_field :name, :placeholder => t("title") %>
	<i class="icon-pencil icon-grey"></i>
</div>

<div class= "description_container">
	<div class="scenario_image picture_container image ">
		<div class="editable active">
			
			<% if @scenario.element_image.url() != "none" %>
				<%= image_tag @scenario.element_image.url(), width:'100%', :class => "image_preview" %>
			<% else %>
				<img class="image_preview" width="100%" src="/images/icon_itec35x40.jpg"/>
			<% end %>				
			<div class= "file_upload">
				<%= f.file_field :element_image, :onchange => "image_preview(this, event);", :class =>"input_element_image" %>
			</div>
		</div>
	</div>
	
	<div class="scenario_description editable active description description_right">
	
		<textarea id="scenario_description" name="scenario[description]" placeholder="<%= t("description") %>"><%= @scenario.description %></textarea>
		<i class="icon-pencil icon-grey"></i>
	</div>
	<div class="clear"></div>
	
	<div class= "select_element_picture_button has_edition_controls active">
		<button onclick= "select_element_picture(this); return false;" class="edition_control"><%= t("select_picture") %></button>
	</div>

	
</div>
<div class="clear"></div>

<div class= "minimizable">
	<hr />			
	<% @scenario.boxes.sort_by{|e| e[:position]}.each do |box| %>
		<div class="box_container <%= box.box_type %>">
			<%= hidden_field_tag :box_id, box.id %>
			<%= hidden_field_tag :box_type, box.box_type %>
			<% box.components.sort_by{|e| e[:position]}.each do |component| %>
				<div class="component_container">
					<%= hidden_field_tag :component_id, component.id %>
					<%= hidden_field_tag :component_type, component.component_type %>
					<%= render :partial => "components/"+component.component_type, :locals => {:component => component}  %>
				</div>
			<%end%>
		
		</div>
		<% if box.box_type == "right_half_box" %>
			<div class="clear"></div>
		<% end %>
	<% end %>			
	<div id="delete_attributes"></div>	
</div>

app/views/scenarios/_form_actions.html.erb
<li>
<%=link_to scenarios_path, :class => "back_icon has_tooltip" do %>
	<img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>		 
<% end %>
</li>
<li>
<%=link_to "", :class => "has_tooltip", :onclick => "save_scenario_form();return false;" do %>
	<img src="/images/white_save.png" title="<%= t('save') %>"></img>
<% end %>
</li>

app/views/scenarios/_header.html.erb
<div id="nav_bar">
			<ul>
				<li class="resources_link"><%= link_to t("Resources"), resources_path %></li>
				<li class="activities_link"><%= link_to t("activities"), activities_path %></li>
				<li class="active guides_link"><%= link_to t("scenarios"), scenarios_path %></li>
				<!--<li class="activity_sequence_link"><%= link_to t("sequences"), activity_sequences_path %></li> -->
				<li class="guides_link"><%= link_to t("guides"), guides_path %></li>
				<li class="experiences_link"><%= link_to t("experiences"), experiences_path %></li>
				<li class="shareboards_link"><%= link_to t("boards") %></li>
			</ul>
		</div>
	</div>
	<div id="section_header" class="resource_header">
		<div id="actions" class="a-left">
			<%= render actions %>
		</div>
		<div id="section_title" class="a-right">
			<p><%= section_title %></p>
		</div>		
	</div>
</header><!-- HEADER -->

app/views/scenarios/_list.html.erb
<% @scenarios.each do |scenario| %>
	<%= render :partial => "elements/element_fixed", :locals => {:element => scenario, :current_layout => current_layout} %>
<% end %>

<div class="clear"></div>

<div class= "paginate_controls active">
	<%= paginate @scenarios,:remote => true, :param_name => "scenarios_page" %>
</div>

app/views/scenarios/_list_actions.html.erb
<li>
	<%= link_to user_root_path do %>
		<img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
	<% end %>	
</li>

<% if current_user != nil %>
	<li>
		<%= link_to request.path + "/new" do %>
			<img src="/images/new_resource.png" title="New"></img>
		<% end %>	
	</li>
<% end %>

<li>
	<%= form_tag request.path, :method => 'get' do %>  
    	<%= text_field_tag :search, params[:search], :class => "subnavbar_search" %>&nbsp;&nbsp;<%= submit_tag t('search'),:class => "search_button_subnavbar" %>  
	<% end %>
</li>

app/views/scenarios/_scenario.html.erb
<%= form_for(@scenario,:html => { :class => "scenario_form" }) do |f_scenario| %>
	<%= render :partial => "scenarios/form" , :locals => {:f => f_scenario, :is_in_guide => false} %>
<% end %>
<input type="hidden" id="edition_mode" value="off"/>
<input type="hidden" id="template_edition_mode" value="off"/>

app/views/scenarios/_scenario_actions.html.erb
<li>
<% if @previous_action == "list" %>
	<%=link_to  "javascript: history.back();", :class => "back_icon has_tooltip" do %>
		<img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
	<% end %>
<% else %>
	<%=link_to  scenarios_path, :class => "back_icon has_tooltip" do %>
		 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>		 
	<% end %>
<% end %>
</li>

<% if current_user != nil && ((@scenario.owner == current_user) or (@scenario.owner_type=="Group" && @scenario.owner.users.exists?(current_user))) %>
	<li>
	<%=link_to edit_scenario_path(@scenario), :class => "has_tooltip" do %>
		 <img src="/images/white_edit.png" title="<%= t('edit') %>"></img>		 
	<% end %>
	</li>
	<li>
	<%=link_to  @scenario, confirm: t('are_you_sure'), method: :delete, :class => "has_tooltip" do %>
		 <img src="/images/white_delete.png" title="<%= t('delete') %>"></img>
	<% end %>
	</li>
<% end %>

app/views/scenarios/_submit.html.erb
<div class="scenario_form_actions form_actions">
	<%= f.submit t("save"), :class => 'scenario_save' %>
</div>

app/views/scenarios/edit.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :Editing_scenario), :actions => "form_actions"} %>

<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'scenarios', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'editing_scenario', :actions => "scenarios/form_actions"} %>
<% end %>

<% content_for :content do %>

	<%= form_for(@scenario,:html => { :class => "scenario_form", :multipart => true }) do |f_scenario| %>
	<div id="element_header">
		<%= render :partial => "generic_partials/ownership_group_small" , :locals => {:edition_mode => @edition_mode,:element => @scenario,:element_type=>"scenario"} %> 
		<hr />
		<div class="clear"></div>
	</div>
	<div id="content_container" class="scenario_container">
			<%= render :partial => "form" , :locals => {:f => f_scenario} %>
			<%= render :partial => "submit", :locals => {:f => f_scenario} %>
		<input type="hidden" id="edition_mode" value="on"/>
		<input type="hidden" id="template_edition_mode" value="off"/>
		
		<div id="elements_library">
			<%= render :partial => "adding_elements" %>
		</div>			
	</div>
	<% end %>

	<script src="/javascript/bootstrap_tooltip.js"></script>
	<script src="/javascript/scenarios_form.js"></script>
<% end %>

app/views/scenarios/index.html.erb
<%= render :partial => "header", :locals => {:section_title => (t (@page)), :actions => "list_actions"} %>


<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'scenarios', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'scenarios', :actions => "scenarios/list_actions"} %>
<% end %>

<% content_for :advanced_search do %>	
	<%= render :partial =>"advanced_search" %>
<% end %>

<% content_for :content do %>

	<div id="content_index">
		<%= render :partial => "list", :locals => { :current_layout => "scenario" }%>
	</div> <!-- CONTENT -->
	
	<script src="/javascript/scenario_index.js"></script>
<% end %>

app/views/scenarios/new.html.erb
<%= render :partial => "header", :locals => {:section_title => (t :new_scenario), :actions => "form_actions"} %>

<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'scenarios', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'new_scenario', :actions => "scenarios/form_actions"} %>
<% end %>

<% content_for :content do %>
	
	<%= form_for(@scenario,:html => { :class => "scenario_form", :multipart => true }) do |f_scenario| %>
		<div id="element_header">
			<%= render :partial => "generic_partials/ownership_group_small" , :locals => {:edition_mode => @edition_mode,:element => @scenario,:element_type=>"scenario"} %> 
			<hr />
			<div class="clear"></div>
		</div>
		<div id="content_container" class="scenario_container">
				
				<%= render :partial => "form" , :locals => {:f => f_scenario} %>
				<%= render :partial => "submit", :locals => {:f => f_scenario} %>
			<input type="hidden" id="edition_mode" value="on"/>
			<input type="hidden" id="template_edition_mode" value="off"/>
			<div id="elements_library">
				<%= render :partial => "adding_elements" %>
			</div>	
		</div>
	<% end %>	

	<script src="/javascript/bootstrap_tooltip.js"></script>
	<script src="/javascript/scenarios_form.js"></script>
<% end %>

app/views/scenarios/show.html.erb
<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'scenarios', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'scenario', :actions => "scenarios/scenario_actions"} %>
<% end %>

<% content_for :content do %>
	<div id="content_container" class="scenario_container">	
		<%= render "scenario" %>
	</div> <!-- CONTENT -->
	<script src="/javascript/bootstrap_tooltip.js"></script>
	<script src="/javascript/scenarios_form.js"></script>
<% end %>