config/routes.rb
    match "/search_results/all_related_elements" => "search_results#all_related_elements" , :as => "all_related_elements"
    match "/search_results/all_best_search_results" => "search_results#all_best_search_results" , :as => "all_best_search_results"
    match "/search_results/load_more_search_results" => "search_results#load_more_search_results" , :as => "load_more_search_results"
    match "/search_results/load_more_related_elements" => "search_results#load_more_related_elements" , :as => "load_more_related_elements"
    resources :search_results
        
    resources :requirements
    match "/activity_sequences/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/:activity_sequence_id/show_activity" => "activity_sequences#show_activity"
    match "/activity_sequences/new_activity_instance" => "activity_sequences#new_activity_instance"
    match "/activity_sequences/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/:activity_sequence_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/activity_sequences/my_activity_sequences" => "activity_sequences#my_activity_sequences" , :as => "my_activity_sequences"
    match "/activity_sequences/pick_it" => "activity_sequences#pick_it" , :as => "pick_it"
    match "/activity_sequences/get_activity" => "activity_sequences#get_activity" , :as => "get_activity"
    match "/activity_sequences/popup_show_activity_sequence" => "activity_sequences#popup_show_activity_sequence" , :as => "popup_show_activity_sequence"
    resources :activity_sequences
    
    match "/guides/show_activity" => "activity_sequences#show_activity"
    match "/guides/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/show_sequence" => "guides#show_sequence"
    match "/guides/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/select_sequence" => "guides#select_sequence"
    match "/guides/get_sequence" => "guides#get_sequence"
    match "/guides/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/new_sequence" => "guides#new_sequence"
    match "/guides/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/recommend_tools" => "guides#recommend_tools"
    match "/guides/recommend_people" => "guides#recommend_people"
    match "/guides/recommend_events" => "guides#recommend_events"
    match "/guides/popup_show_guide" => "guides#popup_show_guide", :as => "popup_show_guide"
    match "/guides/my_guides" => "guides#my_guides" , :as => "my_guides"
    match "/guides/pick_it" => "guides#pick_it" , :as => "pick_it"
    match "/guides/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    match "/guides/:guide_id/show_activity" => "activity_sequences#show_activity"
    match "/guides/:guide_id/show_technological_setting" => "guides#show_technological_setting"
    match "/guides/:guide_id/show_contextual_setting" => "guides#show_contextual_setting"
    match "/guides/:guide_id/show_sequence" => "guides#show_sequence"
    match "/guides/:guide_id/select_technological_setting" => "guides#select_technological_setting"
    match "/guides/:guide_id/new_technological_setting" => "guides#new_technological_setting"
    match "/guides/:guide_id/select_contextual_setting" => "guides#select_contextual_setting"
    match "/guides/:guide_id/new_contextual_setting" => "guides#new_contextual_setting"
    match "/guides/:guide_id/select_sequence" => "guides#select_sequence"
    match "/guides/:guide_id/get_sequence" => "guides#get_sequence"
    match "/guides/:guide_id/get_contextual_setting" => "guides#get_contextual_setting"
    match "/guides/:guide_id/get_technological_setting" => "guides#get_technological_setting"
    match "/guides/:guide_id/new_sequence" => "guides#new_sequence"
    match "/guides/:guide_id/get_assignments_rows" => "activity_sequences#get_assignments_rows"
    match "/guides/:guide_id/recommend_tools" => "guides#recommend_tools"
    match "/guides/:guide_id/recommend_people" => "guides#recommend_people"
    match "/guides/:guide_id/recommend_events" => "guides#recommend_events"
    match "/guides/:guide_id/validate_tool_assignment" => "guides#validate_tool_assignment"

    
    resources :guides
    match "/technological_settings/popup_show_technological_setting" => "technological_settings#popup_show_technological_setting" , :as => "popup_show_technological_setting"
    resources :technological_settings
    match "/contextual_settings/popup_show_contextual_setting" => "contextual_settings#popup_show_contextual_setting" , :as => "popup_show_contextual_setting"
    resources :contextual_settings
    resources :seeds

    match "/experiences/popup_show_experience" => "experiences#popup_show_experience", :as => "popup_show_experience"
    match "/experiences/new/from_guide/:guide_id" => "experiences#new", :as => "new_experience_from_guide"
    match "/experiences/my_experiences" => "experiences#my_experiences" , :as => "my_experiences"
    match "/experiences/get_element_excerpt" => "experiences#get_element_excerpt"    
    resources :experiences

    
    match "/users/popup_show_user" => "users#popup_show_user", :as => "popup_show_user"
    resources :users    
    match "/resources/list_devices" => "resources#list_devices" , :as => "list_devices"
    match "/resources/list_applications" => "resources#list_applications" , :as => "list_applications"
    match "/resources/list_people" => "resources#list_people" , :as => "list_people"
    match "/resources/list_events" => "resources#list_events" , :as => "list_events"            
    resources :resources
    match "/devices/popup_show_device" => "devices#popup_show_device", :as => "popup_show_device"
    resources :devices
    match "/applications/popup_show_application" => "applications#popup_show_application", :as => "popup_show_application"
    resources :applications
    match "/people/popup_show_person" => "people#popup_show_person", :as => "popup_show_person"
    resources :people
    match "/events/popup_show_event" => "events#popup_show_event", :as => "popup_show_event"
    resources :events
    match "/lectures/popup_show_lecture" => "lectures#popup_show_lecture", :as => "popup_show_lecture"
    resources :lectures
    match "/sites/popup_show_site" => "sites#popup_show_site", :as => "popup_show_site"
    resources :sites
    match "/documentaries/popup_show_documentary" => "documentaries#popup_show_documentary", :as => "popup_show_documentary"
    resources :documentaries
    match "/courses/popup_show_course" => "courses#popup_show_course", :as => "popup_show_course"
    resources :courses
    match "/articles/popup_show_article" => "articles#popup_show_article", :as => "popup_show_article"
    resources :articles
    match "/lres/popup_show_lre" => "lres#popup_show_lre", :as => "popup_show_lre"
    resources :lres
    match "/posts/popup_show_posts" => "posts#popup_show_post", :as => "popup_show_post"
    resources :posts
    match "/slideshows/popup_show_slideshows" => "slideshows#popup_show_slideshow", :as => "popup_show_slideshow"
    resources :slideshows
    match "/biographies/popup_show_biographies" => "biographies#popup_show_biography", :as => "popup_show_biography"
    resources :biographies
    match "/documents/popup_show_documents" => "documents#popup_show_document", :as => "popup_show_document"
    resources :documents   
    match "/participants/popup_show_participants" => "forms#popup_show_participant", :as => "popup_show_participant"
    resources :participants   
    match "/reports/popup_show_reports" => "reports#popup_show_report", :as => "popup_show_report"
    match "/reports/load_more_reports_by_section_and_date" => "reports#load_more_reports_by_section_and_date" , :as => "load_more_reports_by_section_and_date"
    match "/reports/index_all" => "reports#index_all", :as => "index_all_reports"
    resources :reports
    match "/widgets/popup_show_reports" => "widgets#popup_show_widget", :as => "popup_show_widget"
    resources :widgets
    match "/klascements/popup_show_klascements" => "klascements#popup_show_klascement", :as => "popup_show_klascement"
    resources :klascements
    match "/artworks/popup_show_artworks" => "artworks#popup_show_artwork", :as => "popup_show_artwork"
    resources :artworks
    match "/reuters_new_items/popup_show_reuters_new_items" => "reuters_new_items#popup_show_reuters_new_item", :as => "popup_show_reuters_new_item"
    resources :reuters_new_items    
    match "/books/popup_show_books" => "books#popup_show_book", :as => "popup_show_book"
    resources :books    
    resources :administrations
    match "/sources/popup_show_sources" => "sources#popup_show_source", :as => "popup_show_source"
    resources :sources
    match "/contents/popup_show_content" => "contents#popup_show_content", :as => "popup_show_content"
    resources :contents
    resources :pictures
  
    match "/groups/popup_show_group" => "groups#popup_show_group", :as => "popup_show_group"
    match "/groups/my_groups" => "groups#my_groups" , :as => "my_groups"
    resources :groups    
    
    match "/comments/new" => "comments#new", :as => "new_comment"
    match "/selectors/paginate_elements" => "selectors#paginate_elements"
    
    match 'home' => 'home#index', as: :user_root
    
    match 'about/faqs' => 'about#faqs', as: :about_faqs
    match 'about/about_us' => 'about#about_us', as: :about_about_us

app/views/reports/_advanced_search.html.erb
<% if @previous_search_params != nil && @previous_search_params[:advanced_search] == "1" %>
<div class="advanced_search row-fluid visible">
<% else %>
<div class="advanced_search row-fluid">
<% end %>
	<div class="span12 advanced_search_padding">
		
		<form class="advanced_search_form" id="advanced_search_form">
			<div class="row-fuid">
				<div class="span3">			
					<div style="margin-top:50px;" class="field_label c_white"><%= t('search_terms') %></div>
					<div>
						<% if @previous_search_params[:search]!=nil && @previous_search_params[:search]!="" %>
							<input type="text" name="search" id="search" value="<%=@previous_search_params[:search]%>"/>
						<% else %>
							<input type="text" name="search" id="search"/>
						<% end %>		
					</div>						
				</div>
				<div class="span2">										
					<div style="margin-top:60px;">
						<button class="button_advanced_search field_label" id="search_button" onclick="submit_advanced_search(event);"><%= t('search') %></button>
						<input type="hidden" id="advanced_search" name="advanced_search" value="0">
					</div>
					
				</div>
				<div class="span4">
															
		
				</div>
				<div class="span3">
					<div class="row-fluid" style="height: 100px;">
						<div class="span11 num_results_advanced_search c_white"><%= t('results')%>:&nbsp;<span id="num_results"></span><%=@num_results%></div>
						<div class="span11 title_advanced_search c_white"  style="margin-top: 20px;"><%= t("search") %> </div>
						<div class="span11 description_advanced_search c_white"><%= t('fill_inputs_and_search') %></div>
						<div class="clear"></div>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>		

app/views/reports/_form.html.erb
<% if @report.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>
	
	  <ul>
	  <% @report.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<% end %>




<!------------ Left column ------------------>
<div class="left_column">
	<div class="report_name field_body">
		<% if @edition_mode==true %>
			<textarea id="report_name" name="report[name]" placeholder="<%= t("title") %>"><%= @report.name %></textarea>
			<i class="icon-pencil icon-grey"></i>
		<% else %>
			<span><%= @report.name %></span>
		<% end %>
	</div>
	
		
	<div class="report_description description field_body">
		<% if @edition_mode==true %>
			<textarea id="report_description" name="report[description]" placeholder="<%= t("description") %>"><%= @report.description %></textarea>
			<i class="icon-pencil icon-grey"></i>
		<% else %>
			<div>
				<% if @report.description != nil %>			
					<%= raw @report.description.truncate(1000, :separator => " ", :omission => "...") %>
				<% end %>
				
			</div>
		<% end %>
	</div>
	
	
	<div class="report_tags element_field_box">
		<div class="field_prompt"><%= t("keywords") %></div>
		<div class="field_body">			
			<% if @edition_mode==true %>    
		    	<textarea id="report_tags" class="tags" name="report[tag_list]"><% if @report!=nil %><%= @report.tag_list %><% end %></textarea>
		    	<i class="icon-pencil icon-grey"></i>
		    <% else %>
		    	<span class="tags"><% if @report!=nil %><%= @report.tag_list_with_links.html_safe %><% end %></span>	
		    <% end %>														
		</div>
	</div>	
	
	<% if @edition_mode != true %>
	<div class="report_section element_field_box">
		<div class="field_prompt"><%= t("section") %></div>
		<div class="field_body">				
			<span><%= @report.section %></span>
		</div>		
	</div>	
	<% end %>
	
	<div class="report_url element_field_box">
		<div class="field_prompt"><%= t("url") %></div>
		<div class="field_body">
			<% if @edition_mode==true %>    
		    	<%= report_form.text_field :url %>
		    	<i class="icon-pencil icon-grey"></i>			    	
		    <% else %>
		    	<a href="<%= @report.url %>" target="_blank"><%= @report.url %></a>
		    <% end %>
	   </div>		
	</div>
	
	<% if @edition_mode!=true && @report.scraped_from!=nil && @report.scraped_from!="" %>  
		<div class="report_scraped_from element_field_box">
			<div class="field_prompt"><%= t("source") %></div>
			<div class="field_body">
				<a href="<%= @report.scraped_from %>" target="_blank"><%= @report.scraped_from %></a>
			</div>
		</div>
	<% end %>
	
	
</div>



<!------------- Right column ---------------->
<div class="right_column">
	<% if @edition_mode == false && @popup == nil %>	
		<div class="watermark_container_show">
			<div class="watermark_show <%=@resource_type.downcase%>_watermark"></div>
		</div>
	<% end %>
	<div class="element_image_box picture_container">
		<% if @edition_mode==true %>	
			<span class="change_element_image has_edition_controls active" onclick= "select_element_image_new(this);"><%= t('change_image') %></span>		
			<% if @report.element_image.url() != "none" %>
				<%= image_tag @report.element_image.url(:medium), width:'100%', :class => "image_preview" %>
			<% else %>
				<%= image_tag "/images/watermarks/b_watermark_report.png", width:'100%', :class => "image_preview" %>
			<% end %>
			<div class= "file_upload">
				<%= report_form.file_field :element_image, :onchange => "image_preview_new(this, event);", :class =>"input_element_image" %>
			</div>
		<% else %>
			<% if @report.element_image.url() != "none" %>
				<%= image_tag @report.element_image.url(:medium), width:'100%', :class => "image_preview_show" %>
			<% else %>
				<%= image_tag "/images/no_photo.png", width:'100%', :class => "image_preview_show" %>
			<% end %>
		<% end %>
	</div>

</div>





<% if @edition_mode==true %>
	<div id="snippets_library" style="display: none">
		<div class="subject_item">				
			<%= select_tag "subject", options_from_collection_for_select(@subjects, "id", "name"), :prompt => "", :class => "subject" %>
			<span class="delete_subject"  onClick="delete_subject(this);">X</span>
		</div>
	</div>
<% end %>

app/views/reports/_form_actions.html.erb
<li>
<%=link_to  reports_path, :class => "back_icon has_tooltip" do %>
	 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
<% end %>
</li>
<li>
<%=link_to "", :class => "has_tooltip", :onclick => "save_report_form();return false;" do %>
	 <img src="/images/white_save.png" title="<%= t('save') %>"></img>
<% end %>
</li>

app/views/reports/_list.html.erb
<div class="search_elements_type_box list_<%= params[:date_range] %>">
	<div class="prompt">
		<img src="/images/black_event_100.png" width="50px" height="30px"/>&nbsp;&nbsp;<%= t(date_range) %>
	</div>
	<div class="body">	
		<% if @num_results == 0 %>
			<div class="no_results"><%= t('no_results')%></div>			
		<% end %>
		
		<% @reports.each do |report| %>
			<%= render :partial => "elements/element_fixed", :locals => {:element => report, :current_layout => current_layout} %>
		<% end %>
		
		<div class="clear"></div>
		
		<div class= "paginate_controls active">
			<%= paginate @reports %>
		</div>
	</div>
</div>

app/views/reports/_list_date_range.html.erb
	
<div class="prompt">
	<img src="/images/<%= date_range %>.png" width="50px"/>&nbsp;&nbsp;<%= t(date_range) %>
	<% if elements.last_page? %>
		<%= image_tag "/images/arrow_right_disabled.png",:class => "arrow_disabled" %>
	<% else %>
		<%= link_to_next_page elements, image_tag("/images/arrow_right.png") ,:remote => true, :params => {:controller => "reports",:action => "load_more_reports_by_section_and_date",:section => section,:date_range => date_range } %>
	<% end %>
	<% if elements.first_page? %>
		<%= image_tag "/images/arrow_left_disabled.png", :class => "arrow_disabled"  %>
	<% else %>
		<%= link_to_previous_page elements, image_tag("/images/arrow_left.png") ,:remote => true, :params => {:controller => "reports",:action => "load_more_reports_by_section_and_date",:section => section,:date_range => date_range } %>
	<% end %>
	<%= link_to t("view_all"), index_all_reports_path(:section => section, :date_range => date_range, :search => params[:search]),:class => "view_all" %>
</div>
<div class="body">
	<% if elements.size > 0 %>
		<% elements.each do |element| %>
			<%= render :partial => "elements/element_fixed", :locals => {:element => element, :current_layout => ""} %>
		<% end %>
	<% else %>
		<div class="no_results"><%= t('no_results')%></div>	
	<% end %>
	<div class="clear"></div>
</div>

app/views/reports/_popup_list_actions.html.erb
<div class= "my_activities_filter disabled" onclick="all_users_popup_filter(this);"><%= t("reports") %></div>
<div class= "my_activities_filter" onclick="current_user_popup_filter(this);"><%= t("my_reports") %></div>
<div class= "my_activities_filter" onclick="bookmarks_current_user_popup_filter(this)"><%= t("bookmarked_reports") %></div>
<div class="current_user_input_copy_container">
	<%= hidden_field_tag :user_id, current_user.id , :class => 'current_user_id' %>	
</div>
<div class="bookmarks_input_copy_container" >
	<%= hidden_field_tag :display_bookmarks, "true", :class => 'display_bookmarks' %>
</div>

<%= form_tag({:action => 'paginate_elements', :controller => 'selectors', :element_class => popup_id, :refresh_popup => 'true'}, :class => "search_form", :method => :get, remote: true) do %>
	<%= text_field_tag :search, params[:search], placeholder: t('enter_search_term') %>
	<div class="search_button" onclick='$("#<%= popup_id %> .search_form").submit()'></div>
	<div class="current_user_input_container"></div>
<% end %>

app/views/reports/_report.html.erb
<%= form_for(@report, :html => { :class => "report_form" }) do |fo| %>
	<%= render :partial => "reports/form" , :locals => {:report_form => fo} %>
<% end %>
<input type="hidden" id="edition_mode" value="off"/>

app/views/reports/_report_actions.html.erb
<li>
<% if @previous_action == "list" %>
	<%=link_to  "javascript: history.back();", :class => "back_icon has_tooltip" do %>
		 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
	<% end %>
<% else %>
	<%=link_to  reports_path, :class => "back_icon has_tooltip" do %>
		 <img src="/images/white_arrow_left.png" title="<%= t('back_to_home') %>"></img>
	<% end %>
<% end %>
</li>
<% if current_user != nil && ((@report.owner == current_user) or (@report.owner_type=="Group" && @report.owner.users.exists?(current_user)))%>
	<li>
	<%=link_to edit_report_path(@report), :class => "has_tooltip" do %>
		 <img src="/images/white_edit.png" title="<%= t('edit') %>"></img>
	</li>
	<% end %>
	<li>
	<%=link_to  @report, confirm: t('are_you_sure'), method: :delete, :class => "has_tooltip" do %>
		<img src="/images/white_delete.png" title="<%= t('delete') %>"></img>
	<% end %>	
	</li>
<% end %>

<li>
	<%= form_tag search_results_path, :method => 'get' do %>  
    	<%= text_field_tag :search, params[:search], :class => "subnavbar_search" %>&nbsp;&nbsp;<%= submit_tag t('search'),:class => "search_button_subnavbar" %>  
	<% end %>
</li>

app/views/reports/_submit.html.erb
<div class="report_form_actions form_actions">
	<%= report_form.submit t("save"), :class => 'report_save' %>
</div>	

app/views/reports/edit.html.erb
<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'editing_report', :actions => "reports/form_actions"} %>
<% end %>

<% content_for :content do %>
	<%= form_for(@report, :html => { :class => "report_form" }) do |f_report| %>
		<div id="element_header">
			<%= render :partial => "generic_partials/ownership_group_small" , :locals => {:edition_mode => @edition_mode,:element => @report,:element_type=>"report"} %> 
			<hr />
			<div class="clear"></div>
		</div>
		<div id="content_container" class="report_container">
			<input type="hidden" id="edition_mode" value="on">
				<%= render :partial => "form" , :locals => {:report_form => f_report} %>
				<%= render :partial => "submit", :locals => {:report_form => f_report} %>			
		</div>			
		<span style="display:none" id="is_edition" data-value="true"></span>	
		
		<script src="/javascript/reports_form.js"></script>
	<% end %>
<% end %>

app/views/reports/load_more_reports_by_section_and_date.js.erb
$(".search_elements_type_box.list_<%= @date_range %>").html("<%=j render :partial => 'list_date_range', locals: { :elements => @elements, :section => @section, :date_range => @date_range } %>");

app/views/reports/new.html.erb
<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'new_report', :actions => "reports/form_actions"} %>
<% end %>

<% content_for :content do %>
	<%= form_for(@report, :html => { :class => "report_form" }) do |f_report| %>
		<div id="element_header">
			<%= render :partial => "generic_partials/ownership_group_small" , :locals => {:edition_mode => @edition_mode,:element => @report,:element_type=>"report"} %> 
			<hr />
			<div class="clear"></div>
		</div>
		<div id="content_container" class="report_container">
			<input type="hidden" id="edition_mode" value="on">
				<%= render :partial => "form" , :locals => {:report_form => f_report} %>
				<%= render :partial => "submit", :locals => {:report_form => f_report} %>
		</div>	
		
		<span style="display:none" id="is_edition" data-value="true"></span>	
		
		<script src="/javascript/reports_form.js"></script>
	<% end%>
<% end %>

app/views/reports/popup_show_report.js.erb
var details = ("<%=j render :partial => 'reports/report' %>");

app/views/reports/show.html.erb
<% content_for :meta do %>
	<%= render :partial => "/generic_partials/meta", :locals => {:element => @report}%>
<% end %>

<% content_for :head do %>
	<%= render :partial => "header/header", :locals => {:element_active => 'resources', :current_layout => "application"} %>
	<%= render :partial => "header/subheader", :locals => {:section_title => 'report', :actions => "reports/report_actions"} %>
<% end %>

<% content_for :content do %>

	<% if current_user != nil%>
		<%= render :partial => "generic_partials/header_show_resource", :locals => {:element => @report} %>	
	<% end %>

	<div id="content_container" class="report_container">
		<%= render "report" %>
		<%= render :partial => "search_results/related_elements_same_type",:locals => {:related_title =>'related_reports'} %>		
	</div> <!-- CONTENT -->
	<%= render :partial => "search_results/related_elements", :locals => {:element_type =>'Report'} %>

	
	<span style="display:none" id="is_edition" data-value="false"></span>	
	
	
	<script src="/javascript/reports_form.js"></script>
<% end %>